export type MediaDetailSegments = {
    $id: string;
    SOM_text: string;
    EOM_text: string;
    TYPE_text: string;
    TimecodeFormat: string;
    DURATION_text: string;
    ID: number;
    TYPE: number;
    PAR_TYPE: number;
    PAR_ID: number;
    PRT_NUM: number;
    SQ_NUM: number;
    PRT_TTL: any;
    SQ_IDX: number;
    PRT_ID: any;
    PRT_ID2: any;
    CTNR_ID: number;
    CTNR_IDX: number;
    VIRT_RL: number;
    OWN_TYP: number;
    OWN_ID: number;
    MIID: number;
    MI_TYP: number;
    EXTERNALLY_OWNED_ID: number;
    GRADE_ID: number;
    GRADED: number;
    AQ: number;
    VQ: number;
    SOM: number;
    SOMS: string;
    EOM: number;
    EOMS: string;
    FPS: number;
    DUR: number;
    DUR_TCS: string;
    OVERLAPS: number;
    FLG: number;
    FLG_EN: number;
    SUBS: number;
    LANG_VS: number;
    TX_OK: number;
    CR_TSKID: number;
    CR_USR: any;
    USE_PAR_AU: number;
    AU_NUM: number;
    AU_NM: any;
    AU_CONT: any;
    AU_LANG: any;
    AU_MS: any;
    AU_NR: any;
    AU_NTS: any;
    AU_SP: any;
    CREATED: string;
    MODIFIED: any;
    CREATED_BY: string;
    MODIFIED_BY: any;
    IN_CUE_CMMTS: any;
    OUT_CUE_CMMTS: any;
    EntityKey: EntityKey;
};

type EntityKey = {
    $id: string;
    EntitySetName: string;
    EntityContainerName: string;
    EntityKeyValues: Array<EntityKeyValues>;
};

type EntityKeyValues = {
    Key: string;
    Value: number;
};