import { VersionSearchDataItem } from '../version/version.search.data.item';
import { MediaSearchDataItem } from '../media/media.search.data.item';
import { TitleSearchDataItem } from '../title/title.search.data.item';

export type AllSearchDataItem = MediaSearchDataItem & VersionSearchDataItem &
            TitleSearchDataItem & {
    $id: string;
    Segments: any;
    AudioTracks: any;
    TV_STD_text: string;
    OWNERS_text: string;
    DURATION_text: string;
    ASPECT_R_text: string;
    AUD_LANGUAGE_ID_text: string;
    USAGE_TYPE_text: string;
    THUMBFILE: string;
    THUMBSERVER: string;
    THUMBID: number;
    PROD_LANGUAGE: string;
    PGM_STATUS_TEXT: string;
    ID: number;
    ITEM_TYPE: number;
    SER_ABS_ID: number;
    SER_ABS2_ID: number;
    SER_TYPE: number;
    SER_EP_NUM: number;
    SER_EP_SQ_NUM: number;
    SER_CT_SQ_NUM: number;
    PGM_ABS_ID: number;
    PGM_RL_ID: number;
    PARENT_ID: number;
    TREE_LEVEL: number;
    TITLE: string;
    SER_TITLE: string;
    SER_NAME: string;
    SER_NUM: number;
    VERSION: string;
    VERSION_TYPE: number;
    SERIESID1: string;
    SERIESID2: string;
    PROGID1: string;
    PROGID2: string;
    VERSIONID1: string;
    VERSIONID2: string;
    DUR: number;
    FLAG_MASTER: number;
    FLAG_MASTER_EN: number;
    NET_GRP_ID: number;
    NET_GRP_NAME: string;
    OWNERS: string;
    CREATED_DT: string;
    CREATED_BY: string;
    MODIFIED_DT: string;
    MODIFIED_BY: string;
    PRGM_ID_INHOUSE: string;
    FROM_EPS: number;
    TO_EPS: number;
    LINE_STD: number;
    TV_STD: number;
    AUD_LANGUAGE_ID: number;
    AU_CONT: string;
    AU_DMS_IDS: string;
    AU_LANG: string;
    AU_MS: string;
    AU_MUSIC_IDS: string;
    AU_NM: string;
    AU_NR: string;
    AU_NTS: string;
    AU_NUM: number;
    AU_SP: string;
    CTX_TEXT_COL: string;
    CTX_IDS_COL: string;
    PRIMARY_THUMB_ID: any;
    EntityKey: any;
};
